# AS per need change the path of volumes and uncomment/comment the volumes which are required.
version: '3'
services:
  privacera_secure_chat:
    platform: linux/amd64
    image: privacera/privacera-securechat:latest
    container_name: privacera_secure_chat
    # set command line arguments  here
    # -e sets environment for SECURE_CHAT_DEPLOYMENT
    command:
      - -e openai_chromadb
    # nginx listener is on 3636. Map it per your need.
    ports:
      - "3636:3636"
#    environment:
#      SECURE_CHAT_DEPLOYMENT: ${SECURE_CHAT_DEPLOYMENT:-openai_chromadb}
    volumes:
      - ${PWD}/custom-configs:/workdir/custom-configs
      - ${PWD}/logs:/workdir/securechat/logs
      - ${PWD}/db:/workdir/securechat/db
      - ${PWD}/data:/workdir/securechat/data
      - ${PWD}/index:/workdir/securechat/index
